apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-collector
  namespace: stock-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-collector
  template:
    metadata:
      labels:
        app: metrics-collector
    spec:
      containers:
      - name: metrics-collector
        image: nileshkishore/mystock-metrics-collector:0.2
        ports:
        - containerPort: 7878

---
apiVersion: v1
kind: Service
metadata:
  name: metrics-collector
  namespace: stock-monitoring
spec:
  type: ClusterIP
  ports:
  - port: 7878
  selector:
    app: metrics-collector
